services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SUBDOMAINS=albertojhdaw2
      - TOKEN=eabbdda1-0bf0-488f-b74c-e65bfbcf5035
      - UPDATE_IP=ipv4
      - LOG_FILE=true
    volumes:
      - /home/ubuntu/duckdns/config:/config
    restart: unless-stopped